.intel_syntax noprefix

.section .text

//void asm_Construct(void *mymap_pointer)
.global asm_Construct
asm_Construct:

    ret
//void asm_Set(void *mymap_pointer, char key, int value)
.global asm_Set
asm_Set:

    ret
//int  asm_Get(const void *mymap_pointer, char key)
.global asm_Get
asm_Get:

    ret
//void asm_Erase(void *mymap_pointer, char key)
.global asm_Erase
asm_Erase:

    ret
//void asm_Print(const void *mymap_pointer)
.global asm_Print
asm_Print:

    ret
